// <auto-generated />
using System;
using HMYS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMYS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMYS.Core.Entities.AnketGonderim", b =>
                {
                    b.Property<int>("GonderimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GonderimID"));

                    b.Property<bool>("KullanildiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("KvkkOnay")
                        .HasColumnType("bit");

                    b.Property<int?>("RandevuID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonKullanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SurveyID")
                        .HasColumnType("int");

                    b.Property<string>("TokenID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GonderimID");

                    b.HasIndex("RandevuID");

                    b.HasIndex("SurveyID");

                    b.ToTable("anket_gonderimleri");
                });

            modelBuilder.Entity("HMYS.Core.Entities.AnketSoru", b =>
                {
                    b.Property<int>("AnketSoruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnketSoruID"));

                    b.Property<int?>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("SiraNo")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyID")
                        .HasColumnType("int");

                    b.HasKey("AnketSoruID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SurveyID");

                    b.ToTable("anket_sorulari");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Birim", b =>
                {
                    b.Property<string>("BolumKodu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BolumKodu");

                    b.ToTable("birimler");
                });

            modelBuilder.Entity("HMYS.Core.Entities.CevapDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseID")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionID");

                    b.HasIndex("ResponseID");

                    b.ToTable("cevap_detay");
                });

            modelBuilder.Entity("HMYS.Core.Entities.CevapMaster", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseID"));

                    b.Property<int?>("GonderimID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToplamSkor")
                        .HasColumnType("int");

                    b.HasKey("ResponseID");

                    b.HasIndex("GonderimID");

                    b.ToTable("cevap_master");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Doktor", b =>
                {
                    b.Property<int>("DoktorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorID"));

                    b.Property<string>("BolumKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DoktorAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoktorID");

                    b.HasIndex("BolumKodu");

                    b.ToTable("doktorlar");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Hasta", b =>
                {
                    b.Property<int>("HastaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HastaID"));

                    b.Property<string>("HastaGsmNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TCKimlikEncrypted")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HastaID");

                    b.ToTable("hastalar");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<int?>("DoktorID")
                        .HasColumnType("int");

                    b.Property<int?>("HastaID")
                        .HasColumnType("int");

                    b.Property<string>("ProtokolNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuID");

                    b.HasIndex("DoktorID");

                    b.HasIndex("HastaID");

                    b.ToTable("randevular");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.ToTable("roller");
                });

            modelBuilder.Entity("HMYS.Core.Entities.SoruTipi", b =>
                {
                    b.Property<int>("SoruTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoruTipiID"));

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoruTipiID");

                    b.ToTable("soru_tipleri");
                });

            modelBuilder.Entity("HMYS.Core.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirimBolumKodu")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EncryptedTc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimBolumKodu");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("HMYS.Core.SoruBankasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoruBankasi");
                });

            modelBuilder.Entity("HMYS.Core.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuidToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnketTanimlari");
                });

            modelBuilder.Entity("HMYS.Core.Entities.AnketGonderim", b =>
                {
                    b.HasOne("HMYS.Core.Entities.Randevu", "Randevu")
                        .WithMany()
                        .HasForeignKey("RandevuID");

                    b.HasOne("HMYS.Core.Survey", "AnketTanim")
                        .WithMany()
                        .HasForeignKey("SurveyID");

                    b.Navigation("AnketTanim");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("HMYS.Core.Entities.AnketSoru", b =>
                {
                    b.HasOne("HMYS.Core.SoruBankasi", "SoruBankasi")
                        .WithMany()
                        .HasForeignKey("QuestionID");

                    b.HasOne("HMYS.Core.Survey", "AnketTanim")
                        .WithMany()
                        .HasForeignKey("SurveyID");

                    b.Navigation("AnketTanim");

                    b.Navigation("SoruBankasi");
                });

            modelBuilder.Entity("HMYS.Core.Entities.CevapDetay", b =>
                {
                    b.HasOne("HMYS.Core.SoruBankasi", "SoruBankasi")
                        .WithMany()
                        .HasForeignKey("QuestionID");

                    b.HasOne("HMYS.Core.Entities.CevapMaster", "CevapMaster")
                        .WithMany()
                        .HasForeignKey("ResponseID");

                    b.Navigation("CevapMaster");

                    b.Navigation("SoruBankasi");
                });

            modelBuilder.Entity("HMYS.Core.Entities.CevapMaster", b =>
                {
                    b.HasOne("HMYS.Core.Entities.AnketGonderim", "AnketGonderim")
                        .WithMany()
                        .HasForeignKey("GonderimID");

                    b.Navigation("AnketGonderim");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Doktor", b =>
                {
                    b.HasOne("HMYS.Core.Entities.Birim", "Birim")
                        .WithMany("Doktorlar")
                        .HasForeignKey("BolumKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Randevu", b =>
                {
                    b.HasOne("HMYS.Core.Entities.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorID");

                    b.HasOne("HMYS.Core.Entities.Hasta", "Hasta")
                        .WithMany("Randevular")
                        .HasForeignKey("HastaID");

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("HMYS.Core.Kullanici", b =>
                {
                    b.HasOne("HMYS.Core.Entities.Birim", null)
                        .WithMany("Kullanicilar")
                        .HasForeignKey("BirimBolumKodu");

                    b.HasOne("HMYS.Core.Entities.Rol", null)
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolID");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Birim", b =>
                {
                    b.Navigation("Doktorlar");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Hasta", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("HMYS.Core.Entities.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
